name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonacion de repositorio
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Compilacion
        run: |
          mvn package
      - name: Analisis SonarCloud
        run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin.3.11.0.3922:sonar \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=paulovegaa \
          -Dsonar.projectKey=paulovegaa_ms-aumento-voto \
          
