name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonacion de repositorio
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: action/setup-java@4.2.1
        with:
          java-verion: '8'
          distribution: 'temurin'
      - name: Compilacion
        run: |
          mvn package
