name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonacion de repositorio
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Compilacion
        run: |
          #mvn package
          echo 'package'
      - name: Analisis SonarCloud
        run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=paulovegaa \
          -Dsonar.projectKey=paulovegaa_ms-aumento-voto
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: paulovegaa
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          tags: paulovegaa/ms-aumento-voto
      
          
